services:
  frontend:
    build:
      context: "./chat-frontend/"
      dockerfile: "./Dockerfile"
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
        restart: true
  api:
    env_file:
      - "chat-api/.env"
    build:
      context: ./chat-api/
      dockerfile: ./Dockerfile-dev
    ports:
      - "8000:8000"
      - "5678:5678" # for python remote debugger
    volumes:
      - ./chat-api:/api
    networks:
      - chat-internal
    depends_on:
      db:
        condition: service_healthy
        restart: true
      email:
        condition: service_healthy
        restart: true
    healthcheck:
      test: "curl --fail http://localhost:8000/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  db:
    build:
      context: ./chat-db/
      dockerfile: ./Dockerfile
    env_file:
      - "chat-db/.env"
    volumes:
      - "./chat-db/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - chat-internal
    restart: unless-stopped
    healthcheck:
      test: "mysqladmin ping -hlocalhost -uroot -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
  email:
    image: foxcpp/maddy:latest
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    env_file:
      - "./chat-email/.env"
    tmpfs:
      - /run/maddy
    healthcheck:
      test: "nc -v -z localhost 25"
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - chat-internal
    volumes:
      - "./chat-email/maddy.conf:/data/maddy.conf:ro"
      - "./chat-email/certificates:/data/tls:ro"
networks:
  chat-internal:
    driver: bridge
volumes:
  db:
    name: "chat-database"
  email:
    name: "chat-email"